### ISSUE TITLE
老哥,库在哪里下载啊

### ISSUE THREAD

**Issue by goateeTom** [jinshuguangze/HearthstoneDeckCoder#1]
com.hearthstoneDeckCoder.google.gson.Gson;
 com.hearthstoneDeckCoder.google.gson.reflect.TypeToken;
org.jsoup.Jsoup;
 org.jsoup.nodes.Document;
上什么网站下载这些呀

**Comment by jinshuguangze** [comment]
现在只是个简陋的命令行程序罢了，还没写外壳儿呢，所以我这些api还没打包进来。。。
这些都是从maven下载的。

**Comment by jinshuguangze** [comment]
现在已经把jsoup和gson打包进来了
